import { Component, AfterViewInit } from '@angular/core';





@Component({
  selector: 'app-cadastro',
  templateUrl: './cadastro.component.html',
  styleUrls: ['./cadastro.component.css']
})
export class CadastroComponent {

  user = {
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    countryCode: '',
    birthdate: '',
    address: '',
    addressInfo: '',
    city: '',
    country: '',
    zipcode: '',
    state: '',
    reference: '',
    baseCurrency: '',
    usPerson: false,
    terms: false,
    receiveNews: false,
    receiveMarketUpdates: false
  };

 

  countries = [
    'Afeganistão',
    'África do Sul',
    'Albânia',
    'Alemanha',
    'Andorra',
    'Angola',
    'Antígua e Barbuda',
    'Arábia Saudita',
    'Argélia',
    'Argentina',
    'Armênia',
    'Austrália',
    'Áustria',
    'Azerbaijão',
    'Bahamas',
    'Bahrein',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Bélgica',
    'Belize',
    'Benin',
    'Bolívia',
    'Bósnia e Herzegovina',
    'Botsuana',
    'Brasil',
    'Brunei',
    'Bulgária',
    'Burkina Faso',
    'Burundi',
    'Butão',
    'Cabo Verde',
    'Camarões',
    'Camboja',
    'Canadá',
    'Catar',
    'Cazaquistão',
    'Chade',
    'Chile',
    'China',
    'Chipre',
    'Colômbia',
    'Comores',
    'Congo',
    'Coreia do Norte',
    'Coreia do Sul',
    'Costa do Marfim',
    'Costa Rica',
    'Croácia',
    'Cuba',
    'Dinamarca',
    'Djibuti',
    'Dominica',
    'Egito',
    'El Salvador',
    'Emirados Árabes Unidos',
    'Equador',
    'Eritreia',
    'Eslováquia',
    'Eslovênia',
    'Espanha',
    'Estados Unidos',
    'Estônia',
    'Eswatini',
    'Etiópia',
    'Fiji',
    'Filipinas',
    'Finlândia',
    'França',
    'Gabão',
    'Gâmbia',
    'Gana',
    'Geórgia',
    'Granada',
    'Grécia',
    'Guatemala',
    'Guiana',
    'Guiné',
    'Guiné Equatorial',
    'Guiné-Bissau',
    'Haiti',
    'Holanda',
    'Honduras',
    'Hungria',
    'Iêmen',
    'Ilhas Marshall',
    'Ilhas Maurício',
    'Índia',
    'Indonésia',
    'Irã',
    'Iraque',
    'Irlanda',
    'Islândia',
    'Israel',
    'Itália',
    'Jamaica',
    'Japão',
    'Jordânia',
    'Kiribati',
    'Kuwait',
    'Laos',
    'Lesoto',
    'Letônia',
    'Líbano',
    'Libéria',
    'Líbia',
    'Liechtenstein',
    'Lituânia',
    'Luxemburgo',
    'Macedônia do Norte',
    'Madagascar',
    'Malásia',
    'Malavi',
    'Maldivas',
    'Mali',
    'Malta',
    'Marrocos',
    'Mauritânia',
    'México',
    'Mianmar',
    'Micronésia',
    'Moçambique',
    'Moldávia',
    'Mônaco',
    'Mongólia',
    'Montenegro',
    'Namíbia',
    'Nauru',
    'Nepal',
    'Nicarágua',
    'Níger',
    'Nigéria',
    'Noruega',
    'Nova Zelândia',
    'Omã',
    'Palau',
    'Panamá',
    'Papua Nova Guiné',
    'Paquistão',
    'Paraguai',
    'Peru',
    'Polônia',
    'Portugal',
    'Quênia',
    'Quirguistão',
    'Reino Unido',
    'República Centro-Africana',
    'República Dominicana',
    'República Tcheca',
    'Romênia',
    'Ruanda',
    'Rússia',
    'Samoa',
    'San Marino',
    'Santa Lúcia',
    'São Cristóvão e Nevis',
    'São Tomé e Príncipe',
    'São Vicente e Granadinas',
    'Seicheles',
    'Senegal',
    'Serra Leoa',
    'Sérvia',
    'Singapura',
    'Síria',
    'Somália',
    'Sri Lanka',
    'Sudão',
    'Sudão do Sul',
    'Suécia',
    'Suíça',
    'Suriname',
    'Tailândia',
    'Taiwan',
    'Tajiquistão',
    'Tanzânia',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad e Tobago',
    'Tunísia',
    'Turcomenistão',
    'Turquia',
    'Tuvalu',
    'Ucrânia',
    'Uganda',
    'Uruguai',
    'Uzbequistão',
    'Vanuatu',
    'Vaticano',
    'Venezuela',
    'Vietnã',
    'Zâmbia',
    'Zimbábue'
  ];

  formatPhoneNumber(phoneNumber: string): string {
    // Remover caracteres indesejados (como traços, pontos e parênteses)
    const cleanedPhoneNumber = phoneNumber.replace(/[-.()]/g, '');

    // Formatar o número de telefone
    let formattedPhoneNumber = '+';

    // Adicionar o código de região (no exemplo, +55 para o Brasil)
    formattedPhoneNumber += cleanedPhoneNumber.substr(0, 2) + ' ';

    // Adicionar o DDD
    formattedPhoneNumber += cleanedPhoneNumber.substr(2, 2) + ' ';

    // Adicionar o primeiro dígito após o DDD
    formattedPhoneNumber += cleanedPhoneNumber.substr(4, 1) + ' ';

    // Adicionar o restante do número de telefone
    formattedPhoneNumber += cleanedPhoneNumber.substr(5);

    return formattedPhoneNumber;
  }

  registerUser() {
    // Aqui você pode fazer a lógica para enviar os dados do usuário para o banco de dados
    console.log('Dados do usuário:', this.user);
    // Implemente a lógica de envio para o banco de dados aqui
  }

}
